name: h_flutter_example_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  build_runner: ^2.4.12
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_generator: ^2.0.1
  http: ^1.2.2
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
